language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - nightly
  - hhvm

env:
  global:
    - PATH="$HOME/.composer/vendor/bin:$PATH"

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  fast_finish: true
  include:
    - php: 5.5
      env: COMPOSER_FLAGS="--prefer-lowest"
    - php: 5.6
      env: SYMFONY_VERSION=2.3.*
    - php: 5.6
      env: SYMFONY_VERSION=2.7.*
    - php: 5.6
      env: SYMFONY_VERSION=2.8.*@dev
    - php: 5.6
      env: SYMFONY_VERSION="3.0.x-dev as 2.8"
    - php: 7.1
      env: SYMFONY_VERSION="^4.0-BETA"
  allow_failures:
    - php: nightly
    - php: hhvm
    - env: SYMFONY_VERSION=2.8.*@dev
    - env: SYMFONY_VERSION="3.0.x-dev as 2.8"

before_script:
  - composer selfupdate
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/symfony:${SYMFONY_VERSION}" --no-update; fi;
  - composer update --prefer-dist --no-interaction $COMPOSER_FLAGS

script: make test
